Keywords: **Multi-criteria decision analysis**, **TOPSIS**, **COPRAS**

In [1]:
import numpy as np

### TOPSIS

#### Step-1: Evaluation matrix
- Features
- Weights
- Criteria

In [2]:
evaluation_matrix = np.array([
    [5, 250, 1.3],
    [7, 220, 1.2],
    [8, 300, 1.1]
])

weights = [1, 1, 1]

criteria = [False, True, False]

In [3]:
height, width = evaluation_matrix.shape

#### Step-2: Normalisation

![Normalisation](https://www.linkpicture.com/q/topsis_1.png)

In [4]:
sqrt_sum = (evaluation_matrix ** 2).sum(axis=0)
    
normalized = evaluation_matrix / sqrt_sum ** 0.5

In [5]:
normalized

array([[0.42562827, 0.55776344, 0.62401997],
       [0.59587957, 0.49083182, 0.57601843],
       [0.68100522, 0.66931612, 0.5280169 ]])

#### Step-3: Weighted matrix

![Weighted matrix](https://www.linkpicture.com/q/topsis_2.png)

In [6]:
weighted = normalized * weights

In [7]:
weighted

array([[0.42562827, 0.55776344, 0.62401997],
       [0.59587957, 0.49083182, 0.57601843],
       [0.68100522, 0.66931612, 0.5280169 ]])

#### Step-4: Alternatives

![Alternatives](https://www.linkpicture.com/q/topsis_3.png)

In [8]:
worst = np.zeros(width)
best = np.zeros(width)

for i in range(width):
    if criteria[i]:
        worst[i] = min(weighted[:, i])
        best[i] = max(weighted[:, i])
        continue
    
    worst[i] = max(weighted[:, i])
    best[i] = min(weighted[:, i])

In [9]:
best

array([0.42562827, 0.66931612, 0.5280169 ])

In [10]:
worst

array([0.68100522, 0.49083182, 0.62401997])

#### Step-5: Distances

- Euclidean distance (L2 distance)

![Worst Distance](https://www.linkpicture.com/q/topsis_4.png)

![Best Distance](https://www.linkpicture.com/q/topsis_5.png)

In [11]:
worst_distance = np.sqrt(np.sum((weighted - worst) ** 2, axis=1))
best_distance = np.sqrt(np.sum((weighted - best) ** 2, axis=1))

In [12]:
worst_distance

array([0.26400233, 0.09772678, 0.20266533])

In [13]:
best_distance

array([0.14717538, 0.25128928, 0.25537696])

#### Step-6: Similarities

![Similarity](https://www.linkpicture.com/q/topsis_6.png)

- s_iw=1 if and only if the alternative solution has the best condition
- s_iw=0 if and only if the alternative solution has the worst condition

In [14]:
worst_similarity = (
    worst_distance / (worst_distance + best_distance)
)

best_similarity = (
    best_distance / (worst_distance + best_distance)
)

In [15]:
best_similarity

array([0.35793618, 0.71999345, 0.55754014])

In [16]:
worst_similarity

array([0.64206382, 0.28000655, 0.44245986])

#### Step-7: Ranking

In [17]:
best_similarity.argsort() + 1

array([1, 3, 2])

### COPRAS

#### Step-1: Evaluation matrix
- Features
- Weights
- Criteria

In [18]:
evaluation_matrix = np.array([
    [5, 250, 1.3],
    [7, 220, 1.1],
    [8, 300, 1.2]
])

types = np.array([1 if c else -1 for c in criteria])
weights = [1, 1, 1]

#### Step-2: Normalisation

![Normalisation](https://www.linkpicture.com/q/copras_1.png)

In [19]:
normalized = evaluation_matrix / np.sum(evaluation_matrix, axis=0)

In [20]:
normalized

array([[0.25      , 0.32467532, 0.36111111],
       [0.35      , 0.28571429, 0.30555556],
       [0.4       , 0.38961039, 0.33333333]])

#### Step-3: Weighted matrix

![Weighted matrix](https://www.linkpicture.com/q/copras_2.png)

In [21]:
weighted = normalized * weights

In [22]:
weighted

array([[0.25      , 0.32467532, 0.36111111],
       [0.35      , 0.28571429, 0.30555556],
       [0.4       , 0.38961039, 0.33333333]])

#### Step-4: Calculate maximization and minimization index
![Minimization](https://www.linkpicture.com/q/copras_3.png)
![Maximization](https://www.linkpicture.com/q/copras_4.png)

In [23]:
sp = np.sum(weighted[:, types == 1], axis=1)
sm = np.sum(weighted[:, types == -1], axis=1)

In [24]:
sp

array([0.32467532, 0.28571429, 0.38961039])

In [25]:
sm

array([0.61111111, 0.65555556, 0.73333333])

#### Step-5: Calculation of the relative weight of each aleternative
![Relative Weight](https://www.linkpicture.com/q/copras_5.png)

In [26]:
Q = sp + ((np.min(sm) * np.sum(sm)) / (sm * np.sum(np.min(sp) / sp)))

In [27]:
Q

array([1.08998145, 0.99913525, 1.02736549])

#### Step-6: Calculation of the utility degree of each alternative
![Utility](https://www.linkpicture.com/q/copras_6.png)

In [28]:
Q / np.max(Q)

array([1.        , 0.91665344, 0.94255319])